<a href="https://colab.research.google.com/github/Inventor-creator/Learning-Machine-Learning-and-Deep-Learning/blob/main/learning_basic_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch.nn as nn
import torch
from torch import relu

In [2]:
# Define a simple model
class SimpleModel(nn.Module):
  def __init__(self):
    super(SimpleModel, self).__init__()
    self.relu = nn.Linear(10, 5) # Input size 10, output size 5
  def forward(self, x):
    return self.relu(x)


# Check CUDA availability
if torch.cuda.is_available():
  device = torch.device('cuda')
  print("CUDA is available! Training on GPU...")
else:
  device = torch.device('cpu')
  print("CUDA is NOT available. Training on CPU...")
# Instantiate the model
model = SimpleModel()
# Move the model to the GPU
model.to(device)
# Create some sample input data
input_data = torch.randn(1, 10)  # Batch size 1, input size 10
# Move the input data to the GPU
input_data = input_data.to(device)
# Perform a forward pass
output = model(input_data)
print("Output:", output)
print("Output Device:", output.device)

CUDA is NOT available. Training on CPU...
Output: tensor([[-0.6107, -1.0945,  1.0777, -0.8083,  0.0191]],
       grad_fn=<AddmmBackward0>)
Output Device: cpu


In [3]:
tensor = torch.randint( size=(5,10,2), low=10 , high=20 )

In [4]:
tensor

tensor([[[16, 14],
         [18, 13],
         [10, 19],
         [18, 15],
         [19, 11],
         [12, 17],
         [14, 18],
         [10, 15],
         [16, 10],
         [14, 17]],

        [[10, 11],
         [10, 19],
         [16, 14],
         [16, 10],
         [13, 10],
         [18, 13],
         [18, 14],
         [11, 12],
         [15, 16],
         [19, 19]],

        [[12, 16],
         [11, 14],
         [13, 17],
         [13, 18],
         [13, 16],
         [11, 10],
         [17, 14],
         [16, 10],
         [14, 18],
         [15, 19]],

        [[18, 15],
         [13, 16],
         [17, 17],
         [17, 12],
         [11, 10],
         [12, 19],
         [19, 18],
         [18, 13],
         [19, 14],
         [10, 14]],

        [[10, 11],
         [18, 11],
         [11, 19],
         [14, 14],
         [17, 12],
         [10, 17],
         [12, 11],
         [13, 11],
         [18, 11],
         [15, 15]]])

In [5]:
tensor2 = torch.arange(50)

In [6]:
tensor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [7]:
tensor2.reshape(5,10,-1)

tensor([[[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12],
         [13],
         [14],
         [15],
         [16],
         [17],
         [18],
         [19]],

        [[20],
         [21],
         [22],
         [23],
         [24],
         [25],
         [26],
         [27],
         [28],
         [29]],

        [[30],
         [31],
         [32],
         [33],
         [34],
         [35],
         [36],
         [37],
         [38],
         [39]],

        [[40],
         [41],
         [42],
         [43],
         [44],
         [45],
         [46],
         [47],
         [48],
         [49]]])

In [8]:
tensor + tensor2.reshape(5,10,-1)

tensor([[[16, 14],
         [19, 14],
         [12, 21],
         [21, 18],
         [23, 15],
         [17, 22],
         [20, 24],
         [17, 22],
         [24, 18],
         [23, 26]],

        [[20, 21],
         [21, 30],
         [28, 26],
         [29, 23],
         [27, 24],
         [33, 28],
         [34, 30],
         [28, 29],
         [33, 34],
         [38, 38]],

        [[32, 36],
         [32, 35],
         [35, 39],
         [36, 41],
         [37, 40],
         [36, 35],
         [43, 40],
         [43, 37],
         [42, 46],
         [44, 48]],

        [[48, 45],
         [44, 47],
         [49, 49],
         [50, 45],
         [45, 44],
         [47, 54],
         [55, 54],
         [55, 50],
         [57, 52],
         [49, 53]],

        [[50, 51],
         [59, 52],
         [53, 61],
         [57, 57],
         [61, 56],
         [55, 62],
         [58, 57],
         [60, 58],
         [66, 59],
         [64, 64]]])

In [32]:
import pandas as pd

df = pd.read_csv('Titanic-Dataset.csv')



In [33]:
print(df.columns)
types = []
for i in df.columns:
  types.append(type(i))

print(types)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


In [34]:
yTarget = df['Survived']

In [35]:
yTarget = yTarget.to_numpy().reshape(-1, 1)


In [36]:
temp = np.array([])
for i in yTarget:
    if i == 0:
        temp = np.append(temp , 1)
    else:
        temp = np.append(temp , 0)



In [37]:
yTarget = np.append(temp.reshape(-1,1) , yTarget , axis=1)

#yTarget = torch.tensor(yTarget , dtype=torch.float32)


In [38]:

yTarget = torch.tensor(yTarget )


In [39]:
df.drop(columns=['Name','Fare','Survived','Ticket'], inplace=True)

In [40]:
?Pipeline

In [41]:
def cabinSort(cabinNum ):

  if cabinNum is np.nan:
    return '0'
  else:
    return cabinNum[0]



df['Cabin'] = df['Cabin'].apply(cabinSort)
df['Embarked'] = df['Embarked'].fillna('nan')

In [42]:
df.isna().any()

PassengerId    False
Pclass         False
Sex            False
Age             True
SibSp          False
Parch          False
Cabin          False
Embarked       False
dtype: bool

In [43]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [44]:
df['Age'].fillna(-1, inplace=True)


/var/folders/5m/_j_596211w579lz0xp790_0m0000gn/T/ipykernel_47900/1435753638.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(-1, inplace=True)


In [50]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
cols = df.columns



transformer = ColumnTransformer([
    ('labelEncoder', OrdinalEncoder() , ['Sex', 'Cabin', "Embarked"]),


], remainder='passthrough')

normalizerPipe = Pipeline(steps=[
    ("transformer" , transformer),
    ("scaler",StandardScaler())
])

df = normalizerPipe.fit_transform(df)

In [51]:
df

array([[ 0.73769513, -0.48846066,  0.58111394, ..., -0.0896342 ,
         0.43279337, -0.47367361],
       [-1.35557354,  1.39832453, -1.93846038, ...,  0.80634954,
         0.43279337, -0.47367361],
       [-1.35557354, -0.48846066,  0.58111394, ...,  0.13436174,
        -0.4745452 , -0.47367361],
       ...,
       [-1.35557354, -0.48846066,  0.58111394, ..., -1.37761082,
         0.43279337,  2.00893337],
       [ 0.73769513,  1.39832453, -1.93846038, ...,  0.13436174,
        -0.4745452 , -0.47367361],
       [ 0.73769513, -0.48846066, -0.67867322, ...,  0.47035564,
        -0.4745452 , -0.47367361]], shape=(891, 8))

In [52]:
df[0]

array([ 0.73769513, -0.48846066,  0.58111394, -1.73010796,  0.82737724,
       -0.0896342 ,  0.43279337, -0.47367361])

In [53]:
cleanedDataTensor = torch.tensor(df)
len(cleanedDataTensor)


891

In [54]:

class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(8, 12),
            nn.ReLU(),
            nn.Linear(12, 6),
            nn.ReLU(),
            nn.Linear(6, 2)
        )

    def forward(self, x):
        x = self.layers(x)
        return x

In [55]:
cleanedDataTensor


tensor([[ 0.7377, -0.4885,  0.5811,  ..., -0.0896,  0.4328, -0.4737],
        [-1.3556,  1.3983, -1.9385,  ...,  0.8063,  0.4328, -0.4737],
        [-1.3556, -0.4885,  0.5811,  ...,  0.1344, -0.4745, -0.4737],
        ...,
        [-1.3556, -0.4885,  0.5811,  ..., -1.3776,  0.4328,  2.0089],
        [ 0.7377,  1.3983, -1.9385,  ...,  0.1344, -0.4745, -0.4737],
        [ 0.7377, -0.4885, -0.6787,  ...,  0.4704, -0.4745, -0.4737]],
       dtype=torch.float64)

In [58]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

model = Network()
loss = nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

dataset = TensorDataset(cleanedDataTensor, yTarget)
dataloader = DataLoader(dataset, batch_size=5, shuffle=True)


In [59]:
epochs = 50

epochNum = []
lossatNum = []

for i in range(epochs):
    for batch in dataloader:
        inputs, targets = batch
        optimizer.zero_grad()
        outputs = model.forward(inputs.to(torch.float32))

        loss_value = loss(outputs, targets)
        loss_value.backward()
        optimizer.step()

    epochNum.append(i+1)
    lossatNum.append(loss_value.item())
    print(f"Epoch {i+1}/{epochs}, Loss: {loss_value.item()}")


Epoch 1/50, Loss: 0.08856838569045067
Epoch 2/50, Loss: 1.4570438861846924
Epoch 3/50, Loss: 0.3066518008708954
Epoch 4/50, Loss: 0.6969528645277023
Epoch 5/50, Loss: 0.07230256497859955
Epoch 6/50, Loss: 0.8452230542898178
Epoch 7/50, Loss: 1.332617148756981
Epoch 8/50, Loss: 1.2724686861038208
Epoch 9/50, Loss: 0.12673217058181763
Epoch 10/50, Loss: 0.030913827940821648
Epoch 11/50, Loss: 0.1706690639257431
Epoch 12/50, Loss: 2.1391152143478394
Epoch 13/50, Loss: 0.1097416914999485
Epoch 14/50, Loss: 0.09025327116250992
Epoch 15/50, Loss: 0.23347312957048416
Epoch 16/50, Loss: 0.0744883194565773
Epoch 17/50, Loss: 0.2368542104959488
Epoch 18/50, Loss: 1.5370011553168297
Epoch 19/50, Loss: 0.37786802649497986
Epoch 20/50, Loss: 0.911421611905098
Epoch 21/50, Loss: 1.0381088256835938
Epoch 22/50, Loss: 0.1870332583785057
Epoch 23/50, Loss: 0.37153545022010803
Epoch 24/50, Loss: 0.13926944881677628
Epoch 25/50, Loss: 0.11111053451895714
Epoch 26/50, Loss: 0.08740389719605446
Epoch 27/50