<a href="https://colab.research.google.com/github/Inventor-creator/Steam-recommendations-predictor-thingy/blob/main/learning_basic_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch.nn as nn
import torch
from torch import relu

In [26]:
# Define a simple model
class SimpleModel(nn.Module):
  def __init__(self):
    super(SimpleModel, self).__init__()
    self.relu = nn.Linear(10, 5) # Input size 10, output size 5
  def forward(self, x):
    return self.relu(x)


# Check CUDA availability
if torch.cuda.is_available():
  device = torch.device('cuda')
  print("CUDA is available! Training on GPU...")
else:
  device = torch.device('cpu')
  print("CUDA is NOT available. Training on CPU...")
# Instantiate the model
model = SimpleModel()
# Move the model to the GPU
model.to(device)
# Create some sample input data
input_data = torch.randn(1, 10)  # Batch size 1, input size 10
# Move the input data to the GPU
input_data = input_data.to(device)
# Perform a forward pass
output = model(input_data)
print("Output:", output)
print("Output Device:", output.device)

CUDA is NOT available. Training on CPU...
Output: tensor([[ 1.7998,  0.3731, -0.7477, -0.4006,  0.3585]],
       grad_fn=<AddmmBackward0>)
Output Device: cpu


In [38]:
?torch.randint

In [90]:
tensor = torch.randint( size=(5,10,2), low=10 , high=20 )

In [94]:
tensor

tensor([[[11, 10],
         [18, 10],
         [19, 12],
         [16, 17],
         [13, 17],
         [16, 15],
         [14, 12],
         [18, 13],
         [14, 15],
         [18, 14]],

        [[11, 15],
         [16, 13],
         [18, 18],
         [15, 18],
         [13, 16],
         [12, 12],
         [10, 14],
         [12, 12],
         [18, 16],
         [15, 13]],

        [[17, 16],
         [15, 13],
         [13, 15],
         [12, 19],
         [14, 15],
         [10, 11],
         [14, 13],
         [13, 13],
         [15, 16],
         [19, 11]],

        [[17, 14],
         [14, 17],
         [10, 13],
         [11, 14],
         [17, 17],
         [10, 10],
         [15, 16],
         [11, 17],
         [10, 19],
         [14, 15]],

        [[15, 10],
         [13, 17],
         [10, 15],
         [13, 15],
         [14, 15],
         [14, 10],
         [17, 11],
         [13, 12],
         [19, 13],
         [10, 18]]])

In [100]:
tensor2 = torch.arange(50)

In [97]:
tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
tensor2.reshape(5,10,-1)

tensor([[[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12],
         [13],
         [14],
         [15],
         [16],
         [17],
         [18],
         [19]],

        [[20],
         [21],
         [22],
         [23],
         [24],
         [25],
         [26],
         [27],
         [28],
         [29]],

        [[30],
         [31],
         [32],
         [33],
         [34],
         [35],
         [36],
         [37],
         [38],
         [39]],

        [[40],
         [41],
         [42],
         [43],
         [44],
         [45],
         [46],
         [47],
         [48],
         [49]]])

In [103]:
tensor + tensor2.reshape(5,10,-1)

tensor([[[11, 10],
         [19, 11],
         [21, 14],
         [19, 20],
         [17, 21],
         [21, 20],
         [20, 18],
         [25, 20],
         [22, 23],
         [27, 23]],

        [[21, 25],
         [27, 24],
         [30, 30],
         [28, 31],
         [27, 30],
         [27, 27],
         [26, 30],
         [29, 29],
         [36, 34],
         [34, 32]],

        [[37, 36],
         [36, 34],
         [35, 37],
         [35, 42],
         [38, 39],
         [35, 36],
         [40, 39],
         [40, 40],
         [43, 44],
         [48, 40]],

        [[47, 44],
         [45, 48],
         [42, 45],
         [44, 47],
         [51, 51],
         [45, 45],
         [51, 52],
         [48, 54],
         [48, 57],
         [53, 54]],

        [[55, 50],
         [54, 58],
         [52, 57],
         [56, 58],
         [58, 59],
         [59, 55],
         [63, 57],
         [60, 59],
         [67, 61],
         [59, 67]]])

In [74]:
tensor2.reshape(-1,6)[0] = 20